version: '3'

services:
  postgres:
    container_name: evolution_postgres
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./evolution_postgres:/var/lib/postgresql/data
    env_file:
      - db.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./evolution_instances:/evolution/instances
      - ./evolution_store:/evolution/store
    env_file:
      - evolution.env
    command: ['node', './dist/src/main.js']
    expose:
      - 8080
    depends_on:
      postgres:
        condition: service_healthy

  node_services:
    container_name: node_services
    build:
      context: ./node_services
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"  # master.js
      - "3001:3001"  # api.js
      - "3010:3010"  # index.js
    volumes:
      - ./node_services:/app
      - ./node_services/temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=3010
    depends_on:
      evolution_api:
        condition: service_started
      postgres:
        condition: service_healthy